name: my-github-action-on-push
on:
  push:
    branches: [ main ]
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6 # or use a .ruby-version file
      - run: ruby on-push.rb
