name: my-github-action-on-push
on:
  push:
    branches: [ master ]
jobs:
  do-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6 # Not needed with a .ruby-version file
      - run: ruby on-push.rb
